config/routes.rb
CustomersBase::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers do
    collection do
      post 'find'
    end 
  end
  resources :messages, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/newcustomer', to: 'customers#new'
  match '/show_customer', to: 'customers#show'
  

  match '/signout', to: 'sessions#destroy'
  match '/signin', to: 'sessions#new'

  match '/signup', to: 'users#new'

  match '/contacts', to: 'static_pages#contacts'
  match '/about', to: 'static_pages#about'

  match '/newmessage', to: 'messages#new'
  match '/mymessages', to: 'messages#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  password_digest :string(255)
#  admin           :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
	  attr_accessible :first_name, :last_name, :password, :password_confirmation, :admin
	  has_secure_password
	  has_many :messages, dependent: :destroy

	  before_save :create_remember_token

	  validates :first_name, presence: true, length: { maximum: 50 }
	  validates :last_name, presence: true, length: { maximum: 50 }, uniqueness: true, :uniqueness => { :case_sensitive => false }
	  validates :password, presence: true, length: { minimum: 6 }
	  validates :password_confirmation, presence: true

	private

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index] # см. AplicationController
  before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @user=User.new
  end

  def create
    @user=User.new(params[:user])
    if @user.save
      flash[:success] = "User '#{@user.first_name} #{@user.last_name}' created "
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success]="User '#{@user.first_name} #{@user.last_name}' has been updated "
      redirect_to users_path
    else
      render "edit"
    end
  end

  def index
    @users=User.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    if User.find(params[:id]).last_name != "Ziryanov" && User.find(params[:id]).last_name != "Base"
      #разрешаем удалять всех кромме админов Зырянов и Base
      User.find(params[:id]).destroy
      flash[:success] = "User has been destroyed"
      redirect_to users_path
    else
      flash[:error] = "Don't try to destroy general Admin"
      redirect_to users_path
    end
  end

  private

  def admin_user
     render file: "public/403", status: 403, layout: false unless signed_in? && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render "shared/error_mesages", object: f.object %>

<%= f.label "First name" %>
<%= f.text_field :first_name %>

<%= f.label "Last name" %>
<%= f.text_field :last_name %>

<%= f.label "Password" %>
<%= f.password_field :password %>

<%= f.label "Confirm password" %>
<%= f.password_field :password_confirmation %>
<br/>
<%= f.check_box :admin %>
<%= f.label  "Admin?", :class => "checkbox inline" %>
<br/>
<br/>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
	<div class = "form">
	<h1> Edit user </h1>
	<%= form_for(@user) do |f| %>
		<%= render 'fields', f:f %>
		<%= f.submit 'Edit user', class: 'btn' %>
	<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
	<h1> All Users </h1>
	<div class="pagination pagination-centered">
	<%= will_paginate %>
	</div>
	<table>
		<tr>
	    	<td> First name </td> 
			<td> Last name </td> 
			<td> Admin? </td>
			<% if current_user.admin? %>
			<td> Edit link </td>
			<td> Delete link </td>
			<% end %>
			<td> Message link </td>
		</tr> 
		<% @users.each do |user| %>
		<tr>
			<td> <%= user.first_name %> </td> 
			<td> <%= user.last_name %> </td> 
			<td> <%= user.admin %> </td> 
			<% if current_user.admin? %>
			<td> <%= link_to 'Edit', edit_user_path(user) if user.last_name != 'Base' %> </td>
			<td> <%= link_to 'Delete', user, method: :delete if user.last_name != 'Base' %> </td>
			<% end %>
			<td> <%= link_to 'Send message', newmessage_path(:id => user) %> </td> 
		</tr>
		<% end %>
	</table>
	<div class="pagination pagination-centered">
	<%= will_paginate %>
	</div>

app/views/users/new.html.erb
<% provide(:title, 'New User') %>
	<div class = "form">
	<h1> Create new user </h1>
	<%= form_for(@user) do |f| %>
		<%= render 'fields', f:f %>
		<%= f.submit 'Create user', class: 'btn' %>
	<% end %>
</div>