config/routes.rb
CustomersBase::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers do
    collection do
      post 'find'
    end 
  end
  resources :messages, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/newcustomer', to: 'customers#new'
  match '/show_customer', to: 'customers#show'
  

  match '/signout', to: 'sessions#destroy'
  match '/signin', to: 'sessions#new'

  match '/signup', to: 'users#new'

  match '/contacts', to: 'static_pages#contacts'
  match '/about', to: 'static_pages#about'

  match '/newmessage', to: 'messages#new'
  match '/mymessages', to: 'messages#index'

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id           :integer          not null, primary key
#  first_name   :string(255)
#  last_name    :string(255)
#  middle_name  :string(255)
#  phone_number :string(255)
#  address      :string(255)
#  info         :text
#  who_updated  :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Customer < ActiveRecord::Base
	attr_accessible :address, :first_name, :info, :last_name, :middle_name, :phone_number, :who_updated


	
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	validates :middle_name, presence: true, length: { maximum: 50 }  
	validates :phone_number, length: { maximum: 50 }
	validates :address, length: { maximum: 100 }
	validates :info, length: { maximum: 500}

	#VALID_REGEX_OF_PH_NOMBER=''
	#validates :phone_number

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_filter :signed_in_user # см. AplicationController

  def new
    @customer = Customer.new
  end

  def create
     @customer=Customer.new(params[:customer])
     @customer.who_updated = current_user.last_name
    if @customer.save
      flash[:success] = "Customer '#{@customer.first_name} #{@customer.last_name}' created "
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    @customer.who_updated = current_user.last_name
    if @customer.update_attributes(params[:customer])
      flash[:success]="Customer '#{@customer.first_name} #{@customer.last_name}' has been updated "
      redirect_to customers_path
    else
      render "edit"
    end
  end

  def show
    @customer = Customer.find(params[:id])
    @updated_user = User.find_by_last_name(@customer.who_updated)
  end

  def index
    @find_customer = Customer.new
    @customers = Customer.paginate(page: params[:page], per_page: 10)
  end

  def destroy
      Customer.find(params[:id]).destroy
      flash[:success] = "Customer has been destroyed"
      redirect_to customers_path
  end

  def find
  
    @customers = Customer.where("first_name=? OR last_name=? OR middle_name=?", params[:find_customer][:first_name], params[:find_customer][:last_name], params[:find_customer][:middle_name]).paginate(page: params[:page], per_page: 10)
    if @customers[0].nil?
      flash[:success] = "Nothing was found"
      @customers = Customer.paginate(page: params[:page], per_page: 10)
      @find_customer = Customer.new
      redirect_to customers_path and return
    else
      @find_customer = Customer.new
      render 'index'
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_fields.html.erb
<%= render "shared/error_mesages", object: f.object %>

<%= f.label "First name" %>
<%= f.text_field :first_name %>

<%= f.label "Last name" %>
<%= f.text_field :last_name %>

<%= f.label "Middle name" %>
<%= f.text_field :middle_name %>

<%= f.label "Phone number" %>
<%= f.text_field :phone_number %>

<%= f.label "Address" %>
<%= f.text_field :address %>

<%= f.label "Info" %>
<%= f.text_area :info, rows: 10 %>
<br />

app/views/customers/edit.html.erb
<% provide(:title, 'Edit Customer') %>
	<div class = "form">
	<h1> Edit customer </h1>
	<%= form_for(@customer) do |f| %>
		<%= render 'fields', f:f %>
		<%= f.submit 'Edit customer', class: 'btn' %>
	<% end %>
</div>

app/views/customers/index.html.erb
<% provide(:title, 'All Customers') %>
	<h1> All Customers </h1>
	
	<div class="inline">

		<%= form_for :find_customer, url: find_customers_path do |f| %>
			<%= f.text_field :first_name, :size => "15", :placeholder=>"First Name" %>
			<%= f.text_field :last_name, :size => "15", :placeholder=>"Last Name" %>
			<%= f.text_field :middle_name, :size => "15", :placeholder=>"Middle Name" %>
			<%= f.submit "Find", class: "btn" %>
		<% end %>

	</div>

	<% if @customers.any? %>
	<div class="pagination pagination-centered">
  	<%= will_paginate @customers %>
  	</div>
	<table>
		<tr>
	    	<td> First name </td> 
			<td> Last name </td> 
			<td> Middle name </td>
			<td> Phone number </td>
			<td> Profile link </td>
			<td> Edit link </td>
			<td> Delete link </td>
		</tr> 
		<% @customers.each do |customer| %>
		<tr>
			<td> <%= customer.first_name %> </td> 
			<td> <%= customer.last_name %> </td> 
			<td> <%= customer.middle_name %> </td> 
			<td> <%= customer.phone_number %> </td>
			<td> <%= link_to 'Profile', show_customer_path(:id => customer)   %> </td>
			<td> <%= link_to 'Edit', edit_customer_path(customer) %> </td>
			<td> <%= link_to 'Delete', customer, method: :delete %> </td>		
		</tr>
		<% end %>
	</table>
	<div class="pagination pagination-centered">
  	<%= will_paginate @customers %>
  	</div>
	<% else %>
	<p> There is no customers in base </p>
	<% end %>

app/views/customers/new.html.erb
<% provide(:title, 'New Customer') %>
	<div class = "form">
	<h1> Create new customer </h1>
	<%= form_for(@customer) do |f| %>
		<%= render 'fields', f:f %>
		<%= f.submit 'Create customer', class: 'btn' %>
	<% end %>
</div>

app/views/customers/show.html.erb
<% provide(:title, "Customer's profile") %>
	<h1> <%= "#{@customer.first_name} #{@customer.last_name}'s profile"  %> </h1> 
	<table>
		<tr>
	    	<td> First name </td>
	    	<td> <%= @customer.first_name %> </td> 
	    </tr> 
	    <tr>
	    	<td> Last name </td>
	    	<td> <%= @customer.last_name %> </td>
	    </tr> 
	     <tr>
	    	<td> Middle name </td>
	    	<td> <%= @customer.middle_name %> </td> 
	    </tr> 
		<tr>
	    	<td> Phone number </td>
	    	<td> <%= @customer.phone_number %> </td> 
	    </tr> 
	    <tr>
	    	<td> Address </td>
	    	<td> <%= @customer.address %> </td> 
	    </tr> 
	<tr> 
	</table>
	<br />
	<table>
		<td> Information: </td>
		<td> <%= @customer.info %> </td>
	</tr>
	</table>
	<br />
	<table>	
	<tr> <td align="left"> 
			<% if @customer.created_at == @customer.updated_at  %>
				 Profile created and updated : <%= time_ago_in_words(@customer.created_at) %>  ago  by <%="#{@updated_user.first_name} #{@updated_user.last_name}" %> 
			<% else %>
		 		Profile updated <%= time_ago_in_words(@customer.updated_at) %> ago by <%="#{@updated_user.first_name} #{@updated_user.last_name}" %>
		 	<% end %>
	 	</td> 
	</tr>
	<tr> 
		<td align="center">
		<%= link_to 'Edit profile', edit_customer_path(@customer), class: 'btn' %> 
		<%= link_to 'Delete profile', @customer, method: :delete, class: 'btn' %>
		</td>
	</tr>
	</table>
			
			
			