config/routes.rb
CustomersBase::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers do
    collection do
      post 'find'
    end 
  end
  resources :messages, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/newcustomer', to: 'customers#new'
  match '/show_customer', to: 'customers#show'
  

  match '/signout', to: 'sessions#destroy'
  match '/signin', to: 'sessions#new'

  match '/signup', to: 'users#new'

  match '/contacts', to: 'static_pages#contacts'
  match '/about', to: 'static_pages#about'

  match '/newmessage', to: 'messages#new'
  match '/mymessages', to: 'messages#index'

end

app/views/layouts/_footer.html.erb
<div><footer>
	<small>
		Designed and developed by Ziryanov Konstantin, Samara 2013.
	</small>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top" >
	<div class = "navbar-inner">
		<div class = "container">
			<%= link_to "CustomerBase", root_path, id: "logo" %>
			<nav>
			<ul class = "nav pull-right">
				<li > <%= link_to "Home", root_path %> </li>
				<li class="divider-vertical"></li>
				<li > <%= link_to "About", about_path %> </li>
				<li class="divider-vertical"></li>
				<li > <%= link_to "Contacts", contacts_path %> </li>
				<li class="divider-vertical"></li>
				<% if signed_in? && current_user.admin? %>
				<li>
			
	  				<button class="btn dropdown-toggle" data-toggle="dropdown"> 
	  					Actions
	    				<span class="caret"></span>
	  				</button>
					<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
						<li><%= link_to "Create user", signup_path %></li>
						<li><%= link_to "All users", users_path %></li>
						<li class="divider"></li>
						<li><%= link_to "Create customer", newcustomer_path %></li>
						<li><%= link_to "All customers", customers_path %></li>
						<li class="divider"></li>
						<li><%= link_to "My messages", mymessages_path %></li>
						<li class="divider"></li>
						<li><%= link_to "Sign out", signout_path %></li>
					</ul>
		
				</li>
				<% elsif signed_in? %>
				<li>
			
	  				<button class="btn dropdown-toggle" data-toggle="dropdown"> 
	  					Actions
	    				<span class="caret"></span>
	  				</button>
					<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
						<li><%= link_to "All users", users_path %></li>
						<li class="divider"></li>
						<li><%= link_to "Create customer", newcustomer_path %></li>
						<li><%= link_to "All customers", customers_path %></li>
						<li class="divider"></li>
						<li><%= link_to "My messages", mymessages_path %></li>
						<li class="divider"></li>
						<li><%= link_to "Sign out", signout_path %></li>
					</ul>
				</li>
				<% end %>
			</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title))%></title>
		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
	</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<div class = "info">
			<% if !signed_in? %>
				<p>You are not signed in!</p>
				<div align = "left"><p>Параметры для входа в приложение: <br /><hr />
					Admin: <br />
					Login: Base <br />
					password: customer
					</p> <hr />
					<p>
					Manager: <br />
					Login: Koen <br />
					password: password </p> 
				</div>
				<%= link_to "Sign in", signin_path, class: "btn" %>
			<% elsif signed_in? %>
				<p> Yo are signed:<p>
				<%= "#{current_user.first_name} #{current_user.last_name}" %>
				<hr />
				You are: <% if current_user.admin? %> Admin <% else %> Manager <% end %>
				<hr />
				<% if current_user.messages.any? %>
				You have <%= link_to "#{current_user.messages.count} messages" ,mymessages_path %> 
				<% else %>
				You have no messages.
				<% end %>
				<hr />
				<%= link_to "Sign out", signout_path, class: "btn" %>
			<% end %>
		</div>
		<div class="general">
			<% flash.each do |key,value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>